### ISSUE TITLE
The mirror versions of each 1.5.0tag and main branch have not been updated

### ISSUE THREAD

**Issue by Lixxcn** [openyurtio/openyurt-helm#19]
eg: https://github.com/openyurtio/openyurt-helm/blob/yurthub-1.5.0/charts/yurt-manager/values.yaml

```
image:
  registry: openyurt
  repository: yurt-manager
  tag: v1.4.0 # should be v1.5.0
```
